myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('students/', include('students.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

students/urls.py
from django.urls import path
from .import views

app_name = 'students'
urlpatterns = [
    path('', views.student_list, name='student_list'),
    path('about/', views.about, name='about'),
    path('add/',views.add_student,name = 'add_student'), 
    path('update/<int:id>/', views.update_student, name='update_student_list'),
    path('delete/<int:id>/',views.delete_student,name = 'delete_student'),  
    path('register/',views.register,name='register'),

]

students/models.py
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, null = True)
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    email = models.EmailField()

    def __str__(self):
        return self.name

students/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['name', 'age', 'email']

    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age < 0:
            raise forms.ValidationError("Age cannot be negative.")
        return age

    def clean_name(self):
        name = self.cleaned_data.get('name')
        if len(name) < 3:
            raise forms.ValidationError("Name must be at least 3 characters.")
        return name

students/views.py
from django.shortcuts import render , redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from .models import Student
from .forms import StudentForm

@login_required
def student_list(request):
    students = Student.objects.filter(user=request.user)
    return render(request, 'students/student_list.html', {'students': students})

def about(request):
    return render(request, 'students/about.html')

@login_required
def add_student(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            student = form.save(commit=False)
            student.user = request.user
            student.save()
            return redirect('students:student_list')
    else:
        form = StudentForm()
    return render(request,'students/add_student.html', {'form': form})

@login_required
def update_student(request,id):
    student = get_object_or_404(Student, id=id, user=request.user)

    if request.method == "POST":
        form = StudentForm(request.POST,instance=student)
        if form.is_valid():
            student.save()
            return redirect('students:student_list')
    else:
        form = StudentForm(instance=student)
    return render(request, 'students/update_student_list.html', {'form': form})

@login_required
def delete_student(request,id):
    student = get_object_or_404(Student, id=id, user=request.user)
    if request.method =="POST":
        student.delete()
        return redirect('students:student_list')
    return render(request, 'students/confirm_delete.html', {'student': student})

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('students:student_list')
    else:
        form = UserCreationForm()
    return render(request,'registration/registor.html',{'form':form})

students/templates/students/about.html
<!DOCTYPE html>
<html>
<head>
    <title>About Page</title>
</head>
<body>

<h1>This is About Page</h1>
<p>Django is powerful 🚀</p>

</body>
</html>

students/templates/students/add_student.html
<h2>Add Student</h2>

<form method="POST" novalidate>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

students/templates/students/confirm_delete.html
<h2>Confirm Delete</h2>

<p>Are you sure you want to delete "{{ student.name }}"?</p>

<form method="POST">
    {% csrf_token %}
    <button type="submit">Yes, Delete</button>
</form>

<a href="{% url 'students:student_list' %}">Cancel</a>

students/templates/students/student_list.html
<h2>Student List</h2>

<p>
    Welcome, {{ request.user.username }} |
    <form method="POST" action="{% url 'logout' %}" style="display:inline;">
    {% csrf_token %}
    <button type="submit">Logout</button>
</form>
    <a href="{% url 'students:add_student' %}">Add Student</a>
</p>

<hr>

<ul>
    {% for student in students %}
        <li>
            {{ student.name }} - {{ student.age }}

            <a href="{% url 'students:update_student_list' student.id %}">
                Edit
            </a>

            <a href="{% url 'students:delete_student' student.id %}">
                Delete
            </a>
        </li>
    {% empty %}
        <li>No students found</li>
    {% endfor %}
</ul>

students/templates/students/update_student_list.html
<h2>Update Student</h2>
<form method="POST" novalidate>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Update</button>
</form>